dist: trusty

language: php

sudo: false

php:
    - 5.6
    - 7.0

env:
    matrix:
        - TEST_SUITE=unit

matrix:
    exclude:
        - php: 7.0

cache:
    directories:
        - $HOME/.composer/cache

install:
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then composer install --prefer-dist; fi"

script:
#    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpdoc run -d Block,Helper,Model,Observer -t build/doc; fi"
    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcs app --standard=vendor/magento-ecg/coding-standard/Ecg --warning-severity=0; fi"
#    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpmd Block/,Helper/,Model/,Observer/,Test/ text cleancode,codesize,controversial,design,naming,unusedcode; fi"
#    - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then php vendor/bin/phpcpd Block/ Helper/ Model/ Observer/ Test/; fi"
